SRCS = ORCGE01.CBL \
       ORCGE02.CBL \
       ORCGE03.CBL \
       ORCGEERR.CBL \
       ORCGEID2.CBL \
       ORCGEID1.CBL \
       ORAPIONCONDR1V2.CBL \
       ORAPION011R1V2.CBL \
       ORAPION010R1V2.CBL \
       ORAPION012R1V2.CBL \
       ORAPION013R1V2.CBL \

top_builddir = ../..
include $(top_builddir)/cobol/Makefile.global

