SRCS = \
	ORCGH01.CBL \
	ORCGH02.CBL \
	ORCGH03.CBL \
	ORCGH04.CBL \
	ORCGH05.CBL \
	ORCGH99.CBL \
	ORCGHERR.CBL \
	ORCGHID1.CBL \
	ORAPI043R1V3.CBL

top_builddir = ../..
include $(top_builddir)/cobol/Makefile.global

