      *****************************************************************
      * Project code name "ORCA"
      * JMA standard receipt software
      * Copyright(C) 2002 JMA (Japan Medical Association)
      *
      * This program is part of "JMA standard receipt software".
      *
      *     This program is distributed in the hope that it will be useful
      * for further advancement in medical care, according to JMA Open
      * Source License, but WITHOUT ANY WARRANTY.
      *     Everyone is granted permission to use, copy, modify and
      * redistribute this program, but only under the conditions described
      * in the JMA Open Source License. You should have received a copy of
      * this license along with this program. If not, stop using this
      * program and contact JMA, 2-28-16 Honkomagome, Bunkyo-ku, Tokyo,
      * 113-8621, Japan.
      *****************************************************************
      *    orca71
      *****************************************************************
           COPY    "E01.INC".
           COPY    "E02.INC".
           COPY    "EERR.INC".
           COPY    "EID1.INC".
           COPY    "EID2.INC".
           COPY    "F01.INC".
           COPY    "FERR.INC".
           COPY    "FID1.INC".
           COPY    "FID2.INC".
      **** ORAPION010R1V2 （位置を下に変更）
      *    COPY    "CPAPILSTV2.INC"
      *                             REPLACING   //APILST-//
      ***                             BY          //APILST01-//.
      *    ORAPIONCONDR1V2     
           COPY    "CPAPILSTV2.INC"
                                   REPLACING   //APILST-//
                                   BY          //APILST02-//.
      *    ORAPION011R2V2
           COPY    "CPAPILSTV2.INC"
                                   REPLACING   //APILST-//
                                   BY          //APILST03-//.
      *    ORAPION010R1V2
           COPY    "CPAPILSTV2.INC"
                                   REPLACING   //APILST-//
                                   BY          //APILST01-//.
      *    ORAPION012R2V2
           COPY    "CPAPILSTV2.INC"
                                   REPLACING   //APILST-//
                                   BY          //APILST04-//.
      *    ORAPION013R2V2
           COPY    "CPAPILSTV2.INC"
                                   REPLACING   //APILST-//
                                   BY          //APILST05-//.
