\set ON_ERROR_STOP

alter table tbl_wksryact
  alter column inputcoment_1 type character varying(140),
  alter column inputchi1_1 type character varying(10),
  alter column inputchi1_2 type character varying(10),
  alter column inputchi1_3 type character varying(10),
  alter column inputchi1_4 type character varying(10),
  alter column inputchi1_5 type character varying(10),
  alter column inputcoment_2 type character varying(140),
  alter column inputchi2_1 type character varying(10),
  alter column inputchi2_2 type character varying(10),
  alter column inputchi2_3 type character varying(10),
  alter column inputchi2_4 type character varying(10),
  alter column inputchi2_5 type character varying(10),
  alter column inputcoment_3 type character varying(140),
  alter column inputchi3_1 type character varying(10),
  alter column inputchi3_2 type character varying(10),
  alter column inputchi3_3 type character varying(10),
  alter column inputchi3_4 type character varying(10),
  alter column inputchi3_5 type character varying(10),
  alter column inputcoment_4 type character varying(140),
  alter column inputchi4_1 type character varying(10),
  alter column inputchi4_2 type character varying(10),
  alter column inputchi4_3 type character varying(10),
  alter column inputchi4_4 type character varying(10),
  alter column inputchi4_5 type character varying(10),
  alter column inputcoment_5 type character varying(140),
  alter column inputchi5_1 type character varying(10),
  alter column inputchi5_2 type character varying(10),
  alter column inputchi5_3 type character varying(10),
  alter column inputchi5_4 type character varying(10),
  alter column inputchi5_5 type character varying(10);
