\set ON_ERROR_STOP
--
-- オンライン資格確認結果情報格納テーブル
--
-- Create Date : 2020/9/7
--

CREATE TABLE tbl_onshi_kaku (
    hospnum smallint DEFAULT 0 NOT NULL,
    tbl_uuid character varying(36) NOT NULL,
    aite_uuid character varying(36),
    oya_uuid character varying(36),
    orca_err_code character varying(02),
    set_ptid character varying(01),
    orca_sikaku_yuko character varying(01),
    kaku_renumber smallint DEFAULT 0 ,
    kaku_endflg character varying(2) ,
    kaku_kakuninymd character varying(8),
    kaku_kakuninhms character varying(6),
    shou_renumber smallint DEFAULT 0 ,
    shou_endflg character varying(2),
    yakuzai_renumber smallint DEFAULT 0 ,
    yakuzai_endflg character varying(2),
    kenshin_renumber smallint DEFAULT 0 ,
    kenshin_endflg character varying(2),
    ptid bigint DEFAULT 0 NOT NULL,
    fukusu_gaito character varying(1),
    shori_time character varying(14),
    kakuninymd character varying(08),
    hospcd character varying(10),
    file_sikibetu character varying(50),
    shokai_kbn character varying(01),
    result_kbn character varying(01),
    err_code character varying(09),
    err_msg character varying(120),
    code_type character varying(01),
    sho_hknjanum character varying(08),
    sho_kigo character varying(80),
    sho_num character varying(80),
    sho_edaban character varying(02),
    sho_birthday character varying(08),
    sho_douiflg character varying(01),
    result character varying(01),
    result_code character varying(09),
    result_msg character varying(120),
    sikaku_yuko character varying(01),
    card_class character varying(02),
    res_hknjanum character varying(08),
    res_kigo character varying(80),
    res_num character varying(80),
    res_edaban character varying(02),
    res_honkzkkbn character varying(01),
    res_hihknjaname character varying(100),
    res_name character varying(100),
    res_name_etc character varying(100),
    res_kananame character varying(100),
    res_kananame_etc character varying(100),
    res_sex1 character varying(01),
    res_sex2 character varying(01),
    res_birthday character varying(08),
    res_adrs character varying(250),
    res_post character varying(08),
    skkgetymd character varying(08),
    tekstymd character varying(08),
    tekedymd character varying(08),
    ftnrate character varying(03),
    misyugaku character varying(01),
    loss_jiyu character varying(02),
    hknjanum_name character varying(128),
    elder_skkgetymd character varying(08),
    elder_tekstymd character varying(08),
    elder_tekedymd character varying(08),
    elder_ftnrate character varying(03),
    gendo_douiflg character varying(01),
    gendo_time character varying(14),
    gendo_shokbn character varying(02),
    gendo_tekkbn character varying(03),
    gendo_skkgetymd character varying(08),
    gendo_tekstymd character varying(08),
    gendo_tekedymd character varying(08),
    gendo_skjgnstymd character varying(08),
    sikkan_douiflg character varying(01),
    sikkan_time character varying(14),
    sikkan_sipkbn1 character varying(01),
    sikkan_skjgnstymd1 character varying(08),
    sikkan_tekstymd1 character varying(08),
    sikkan_tekedymd1 character varying(08),
    sikkan_ftnmoney1 character varying(06),
    sikkan_sipkbn2 character varying(01),
    sikkan_skjgnstymd2 character varying(08),
    sikkan_tekstymd2 character varying(08),
    sikkan_tekedymd2 character varying(08),
    sikkan_ftnmoney2 character varying(06),
    sikkan_sipkbn3 character varying(01),
    sikkan_skjgnstymd3 character varying(08),
    sikkan_tekstymd3 character varying(08),
    sikkan_tekedymd3 character varying(08),
    sikkan_ftnmoney3 character varying(06),
    kenshin_douiflg character varying(01),
    kenshin_time character varying(14),
    kenshin_kigenymd character varying(08),
    yakuzai_douiflg character varying(01),
    yakuzai_time character varying(14),
    yakuzai_kigen character varying(14),
    sikibetu character varying(50),
    shokai_num character varying(50),
    mod_flg character varying(01),
    lock_kbn character varying(01),
    termid character varying(64),
    opid character varying(16),
    creymd character varying(08),
    crehms character varying(06),
    upymd character varying(08),
    uphms character varying(06)
);
ALTER TABLE ONLY tbl_onshi_kaku
    ADD CONSTRAINT tbl_onshi_kaku_primary_key PRIMARY KEY (hospnum, tbl_uuid);

CREATE INDEX idx_onshi_kaku_ptid ON tbl_onshi_kaku USING btree (ptid);
CREATE INDEX idx_onshi_kaku_hkn ON tbl_onshi_kaku USING btree (res_hknjanum,res_kigo,res_num);
CREATE INDEX idx_onshi_kaku_kymd ON tbl_onshi_kaku USING btree (kaku_kakuninymd);
CREATE INDEX idx_onshi_kaku_ouid ON tbl_onshi_kaku USING btree (oya_uuid);
