SRCS = ORCGY01.CBL \
       ORCGY03.CBL \
       ORCGY04.CBL \
       ORCGY05.CBL \
       ORCGYERR.CBL \
       ORCHC14.CBL \
       ORCHC15.CBL \
       ORCGY011.CBL \
       ORCGY012.CBL \
       ORCGYID1.CBL \
       ORAPI014S1V2.CBL \
       ORAPION001R1V2.CBL \
       ORAPION002R1V2.CBL \
       ORAPION003R1V2.CBL \
       ORAPION004R1V2.CBL \
       ORAPION005R1V2.CBL \
       ORAPION006R1V2.CBL \
       ORAPION007R1V2.CBL \
       ORCGY06.CBL \
       ORAPION008R1V2.CBL \
       ORAPION009R1V2.CBL \


top_builddir = ../..
include $(top_builddir)/cobol/Makefile.global

